# conky configuration
##############################################
# Settings
##############################################
background yes
use_xft yes
xftfont JetBrainsMono Nerd Font Mono:size=10
xftalpha 1
update_interval 1.0
total_run_times 0
own_window yes
own_window_transparent yes
##############################################
## cairo-compmgr
own_window_type desktop
own_window_argb_visual yes
##############################################
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
double_buffer yes
minimum_size 400
maximum_width 400
draw_shades no
draw_outline no
draw_borders no
draw_graph_borders no
default_color 000000
default_shade_color 000000
default_outline_color 828282
alignment top_left
gap_x 120
gap_y 35
no_buffers yes
uppercase no
cpu_avg_samples 2
override_utf8_locale no
##############################################
#  Output
##############################################

TEXT
${font JetBrainsMono Nerd Font Mono:bold:size=10}SYSTEM
${hr}
${font JetBrainsMono Nerd Font Mono:bold:size=10}IP: $alignr ${addr wlan0}
${font JetBrainsMono Nerd Font Mono:bold:size=10}HOST:$alignr$nodename
${font JetBrainsMono Nerd Font Mono:bold:size=10}UPTIME:$alignr$uptime_short

${font JetBrainsMono Nerd Font Mono:bold:size=10}PROCESSORS
${hr}
${font JetBrainsMono Nerd Font Mono:normal:size=10}${cpugraph cpu0}
Total: ${cpu cpu0}% ${cpubar cpu0}
CPU1: ${cpu cpu1}% ${cpubar cpu1}
CPU2: ${cpu cpu2}% ${cpubar cpu2}
CPU3: ${cpu cpu3}% ${cpubar cpu3}
CPU4: ${cpu cpu4}% ${cpubar cpu4}
CPU5: ${cpu cpu5}% ${cpubar cpu5}
CPU6: ${cpu cpu6}% ${cpubar cpu6}
CPU7: ${cpu cpu7}% ${cpubar cpu7}
CPU8: ${cpu cpu8}% ${cpubar cpu8}

${font JetBrainsMono Nerd Font Mono:bold:size=10}MEMORY
${hr}
${font JetBrainsMono Nerd Font Mono:normal:size=10}RAM $alignc $mem / $memmax $alignr $memperc%
$membar
SWAP $alignc ${swap} / ${swapmax} $alignr ${swapperc}%
${swapbar}

${font JetBrainsMono Nerd Font Mono:bold:size=10}STORAGE
${hr}
${font JetBrainsMono Nerd Font Mono:normal:size=10}root $alignc ${fs_used /} / ${fs_size /} $alignr $fs_free_perc%
${fs_bar /}

${font JetBrainsMono Nerd Font Mono:bold:size=10}TOP PROCESSES
${hr}
${font JetBrainsMono Nerd Font Mono:normal:size=10}${top_mem name 1}${alignr}${top mem 1} %
${top_mem name 2}${alignr}${top mem 2} %
$font${top_mem name 3}${alignr}${top mem 3} %
$font${top_mem name 4}${alignr}${top mem 4} %
$font${top_mem name 5}${alignr}${top mem 5} %
$font${top_mem name 6}${alignr}${top mem 6} %
$font${top_mem name 7}${alignr}${top mem 7} %
$font${top_mem name 8}${alignr}${top mem 8} %
$font${top_mem name 9}${alignr}${top mem 9} %
$font${top_mem name 10}${alignr}${top mem 10} %

${font JetBrainsMono Nerd Font Mono:bold:size=10}NETWORK
${hr}
Signal: $alignr ${wireless_link_qual_perc wlan0}%
${downspeedgraph wlan0}
Download: ${downspeed wlan0} $alignr Total: ${totaldown wlan0}
${upspeedgraph wlan0}
Upload: ${upspeed wlan0} $alignr Total: ${totalup wlan0}
